default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace # Remove trailing spaces
        args: [--markdown-linebreak-ext=md]
        exclude: ^\.github/.*$
      - id: end-of-file-fixer # Add newline to end of files

  - repo: https://gitlab.com/pycqa/flake8
    rev: ""
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: ["flake8-blind-except", "flake8-tidy-imports"]

  - repo: https://github.com/timothycrosley/isort
    rev: ""
    hooks:
      - id: isort
