{{- $chart := .Chart -}}
{{- $values := .Values -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}
  labels:
    app: {{ template "application.name" . }}
    environment: {{ $values.labels.environment | quote }}
    repo: {{ $values.labels.repo | quote }}
    team: {{ (index $chart.Maintainers 0).Name }}
    version: {{ $chart.Version | quote }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "application.name" . }}
